#服务器配置
server:
  #端口
  port: 8087
  #启动压缩
  compression:
    enabled: true

#spring配置
spring:
  #数据库配置
  datasource:
    url: jdbc:mysql://47.93.198.105:3306/ys_test?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 4e3w4s3a
    driver-class-name: com.mysql.jdbc.Driver
  #redis
  redis:
    host: 47.93.198.105
    port: 6379
    password: liusihua6666
    # 连接池最大连接数（使用负值表示没有限制）
    pool.max-active: -1
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    pool.max-wait: -1
    # 连接池中的最大空闲连接
    pool.max-idle: 8
    # 连接池中的最小空闲连接
    pool.min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 0

#日志级别
logging:
  level:
    com:
      mlink: debug




