#服务器配置
server:
  #端口
  port: 8081
  #启动压缩
  compression:
    enabled: true

#spring配置
spring:
  #应用配置
  application:
    #名称:
    name: inventory-service
  #数据库配置
  datasource:
    url: jdbc:mysql://47.104.172.218:3306/ys?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 4e3w4s3a
    driver-class-name: com.mysql.jdbc.Driver
  #redis
  redis:
    host: 47.104.172.218
    port: 6379
    password: 4e3w4s3a
    # 连接池最大连接数（使用负值表示没有限制）
    pool.max-active: -1
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    pool.max-wait: -1
    # 连接池中的最大空闲连接
    pool.max-idle: 8
    # 连接池中的最小空闲连接
    pool.min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 0

  #404交给异常处理器处理
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

#mybatis
mybatis:
  typeAliasesPackage: com.**.**.entity
  mapperLocations: classpath:com/**/**/mapper/*.xml

#日志级别
logging:
  level:
    com:
      mlink: debug

#swagger
pringfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

##服务器发现注册配置
#eureka:
#  client:
#    serviceUrl:
#      #配置服务中心(可配置多个,用逗号隔开)
#      defaultZone: http://localhost:9980/eureka/
#    #eureka client刷新本地缓存时间
#    registryFetchIntervalSeconds: 5
#  #将swagger页面,集成到到eureka中心
#  instance:
#    status-page-url: http://localhost:${server.port}/swagger-ui.html
#    #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
#    #注意，EurekaServer一定要设置eureka.server.eviction-interval-timer-in-ms否则这个配置无效，这个配置一般为服务刷新时间配置的三倍
#    lease-expiration-duration-in-seconds: 15
#    #服务刷新时间配置，每隔这个时间会主动心跳一次
#    lease-renewal-interval-in-seconds: 5
#
##feign开启降级服务
#feign:
#  hystrix:
#    enabled: true
#
##ribbon   开启Ribbon的饥饿加载模式
#ribbon:
#  eager-load:
#    enabled: true
#    #指定需要饥饿加载的客户端名称、服务名
#    clients: user-service
#  #eureka客户端ribbon刷新时间
#  ServerListRefreshInterval: 5000
#
##hystrix    熔断服务 转发等待时长
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 60000


